name = "hadlink_core"
description = "SPARK core for hadlink URL shortener"
version = "0.1.0-dev"
licenses = "AGPL-3.0-or-later"

[[depends-on]]
gnatprove = "^14.1.1"

[[depends-on]]
sparknacl = "^4.0.1"

[gpr-set-externals]
SPARKNACL_LIBRARY_TYPE = "static-pic"
